<?php

return [
    'youtube' => [
        'label' => 'YouTube',
        'icon' => 'yt',
        'color' => '#FF0000',
        'auth_type' => 'oauth',
        'text_limit' => null,
        'media_required' => 'video',
        'media_allowed' => ['video'],
        'analytics_tier' => 1,
        'supports_text_only' => false,
    ],
    'facebook' => [
        'label' => 'Facebook Page',
        'icon' => 'fb',
        'color' => '#1877F2',
        'auth_type' => 'oauth',
        'text_limit' => 63206,
        'media_required' => null,
        'media_allowed' => ['image', 'video', 'link'],
        'analytics_tier' => 1,
        'supports_text_only' => true,
    ],
    'instagram' => [
        'label' => 'Instagram',
        'icon' => 'ig',
        'color' => '#E4405F',
        'auth_type' => 'oauth',
        'text_limit' => 2200,
        'media_required' => 'image_or_video',
        'media_allowed' => ['image', 'video', 'carousel'],
        'analytics_tier' => 1,
        'supports_text_only' => false,
    ],
    'threads' => [
        'label' => 'Threads',
        'icon' => 'th',
        'color' => '#000000',
        'auth_type' => 'oauth',
        'text_limit' => 500,
        'media_required' => null,
        'media_allowed' => ['image', 'video'],
        'analytics_tier' => 2,
        'supports_text_only' => true,
    ],
    'bluesky' => [
        'label' => 'Bluesky',
        'icon' => 'bs',
        'color' => '#0285FF',
        'auth_type' => 'password',
        'text_limit' => 300,
        'media_required' => null,
        'media_allowed' => ['image'],
        'analytics_tier' => 2,
        'supports_text_only' => true,
    ],
    'mastodon' => [
        'label' => 'Mastodon',
        'icon' => 'ma',
        'color' => '#6364FF',
        'auth_type' => 'oauth',
        'text_limit' => 500,
        'media_required' => null,
        'media_allowed' => ['image', 'video'],
        'analytics_tier' => 2,
        'supports_text_only' => true,
    ],
    'x' => [
        'label' => 'X (Twitter)',
        'icon' => 'x',
        'color' => '#000000',
        'auth_type' => 'oauth',
        'text_limit' => 280,
        'media_required' => null,
        'media_allowed' => ['image', 'video', 'poll'],
        'analytics_tier' => 1,
        'supports_text_only' => true,
    ],
    'tiktok' => [
        'label' => 'TikTok',
        'icon' => 'tk',
        'color' => '#000000',
        'auth_type' => 'oauth',
        'text_limit' => 2200,
        'media_required' => 'video',
        'media_allowed' => ['video'],
        'analytics_tier' => 1,
        'supports_text_only' => false,
    ],

    'pinterest' => [
        'label' => 'Pinterest',
        'icon' => 'pi',
        'color' => '#BD081C',
        'auth_type' => 'oauth',
        'text_limit' => 500,
        'media_required' => 'image_or_video',
        'media_allowed' => ['image'],
        'analytics_tier' => 2,
        'supports_text_only' => false,
    ],

    'linkedin_profile' => [
        'label' => 'LinkedIn Profile',
        'icon' => 'li',
        'color' => '#0A66C2',
        'auth_type' => 'oauth',
        'text_limit' => 3000,
        'media_required' => null,
        'media_allowed' => ['image', 'video'],
        'analytics_tier' => 1,
        'supports_text_only' => true,
    ],

    'linkedin_company' => [
        'label' => 'LinkedIn Company',
        'icon' => 'lc',
        'color' => '#0A66C2',
        'auth_type' => 'oauth',
        'text_limit' => 3000,
        'media_required' => null,
        'media_allowed' => ['image', 'video'],
        'analytics_tier' => 1,
        'supports_text_only' => true,
    ],
];
